### ISSUE TITLE
Move site to picoquery.little-b.it

### ISSUE THREAD

**Issue by divinity76** [rosell-dk/picoQuery#1]
screenshot: 
![image](https://user-images.githubusercontent.com/1874996/69761382-86420a00-1167-11ea-973b-9d0687041c23.png)

**Comment by divinity76** [comment]
just saw that this was closed - the github about section still needs an update: 
![image](https://user-images.githubusercontent.com/1874996/171001393-b7b52185-832e-4af9-b30f-114f826d302d.png)

**Comment by rosell-dk** [comment]
Thanks :)
I updated it
